package constants

const (
	Status   = "status"
	Message  = "message"
	Response = "resp"
)

//User Roles
const (
	Owner     = 1
	Developer = 2
	Tester    = 3
)

//
const (
	NOT_PART_OF_THE_PROJECT = "NOT_PART_OF_THE_PROJECT"
	PROJECT_DELETE_SUCCESS  = "PROJECT_DELETE_SUCCESS"
	PROJECT_DELETE_ERROR    = "PROJECT_DELETE_ERROR"
	ACTION_NOT_AUTHORIZED   = "ACTION_NOT_AUTHORIZED"
	BAD_REQUEST             = "BAD_REQUEST"
	SPRINT_ALREADY_EXISTS   = "SPRINT_EXISTS"
	PROJECT_ALREADY_EXISTS  = "PROJECT_EXISTS"
	WRONG_DATE_FORMAT       = "WRONG_DATE_FORMAT"
	NOT_VALID_SPRINT        = "INVALID_SPRINT"
	SPRINT_DELETE_SUCCESS   = "SPRINT_DELETE_SUCCESS"
	USER_DOESNT_EXIST       = "USER_DOESNOT_EXIST"
	ISSUE_DELETE_SUCCESS    = "ISSUE_DELETE_SUCCESS"
)

const (
	SPRINT_DATE_FORMAT = "2006-01-02"
)
